# --- Settings for Lattice ICE40UP5K
DEVICE = UP5K
PACKAGE = sg48
# --- Settings for CologneChip GateMate A1
#DEVICE = CCGM1A1

# --- Settings for the design
TOP = TOP_MODULE
FREQ = 20


SRC_DIR = designs
include scripts/config.mk
